services:
  web:
    build: .
    ports:
      - "811:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oleg -d comments"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
EOF