services:
  web:
    build: .
    ports:
      - "811:80"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy  # Это лучше, чем просто depends_on

  db:
    image: postgres:18
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql  # ИЗМЕНИТЕ ЭТО! Убрать /data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: