services:
  web:
    build: .
    ports:
      - "811:80"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:18
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      # Изменяем точку монтирования для PostgreSQL 18+
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oleg -d comments"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge